/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZikirRouteImport } from './routes/zikir'
import { Route as KumpulanDoaRouteImport } from './routes/kumpulan-doa'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran/index'
import { Route as QuranSurahRouteImport } from './routes/quran/$surah'

const ZikirRoute = ZikirRouteImport.update({
  id: '/zikir',
  path: '/zikir',
  getParentRoute: () => rootRouteImport,
} as any)
const KumpulanDoaRoute = KumpulanDoaRouteImport.update({
  id: '/kumpulan-doa',
  path: '/kumpulan-doa',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahRoute = QuranSurahRouteImport.update({
  id: '/quran/$surah',
  path: '/quran/$surah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/kumpulan-doa': typeof KumpulanDoaRoute
  '/zikir': typeof ZikirRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/kumpulan-doa': typeof KumpulanDoaRoute
  '/zikir': typeof ZikirRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/kumpulan-doa': typeof KumpulanDoaRoute
  '/zikir': typeof ZikirRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/kumpulan-doa'
    | '/zikir'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/kumpulan-doa'
    | '/zikir'
    | '/quran/$surah'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/kumpulan-doa'
    | '/zikir'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  KumpulanDoaRoute: typeof KumpulanDoaRoute
  ZikirRoute: typeof ZikirRoute
  QuranSurahRoute: typeof QuranSurahRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zikir': {
      id: '/zikir'
      path: '/zikir'
      fullPath: '/zikir'
      preLoaderRoute: typeof ZikirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kumpulan-doa': {
      id: '/kumpulan-doa'
      path: '/kumpulan-doa'
      fullPath: '/kumpulan-doa'
      preLoaderRoute: typeof KumpulanDoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surah': {
      id: '/quran/$surah'
      path: '/quran/$surah'
      fullPath: '/quran/$surah'
      preLoaderRoute: typeof QuranSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  KumpulanDoaRoute: KumpulanDoaRoute,
  ZikirRoute: ZikirRoute,
  QuranSurahRoute: QuranSurahRoute,
  QuranIndexRoute: QuranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
